/** Finding codes and their categories. No imports, so the browser can use it. */

/** Why a finding exists, so an integrator can branch on the kind of failure. */
export type FindingCategory = "UNSUPPORTED" | "SIMULATION_FAILED" | "INTENT_MISMATCH" | "POLICY_VIOLATION" | "INVALID_REQUEST";

export type FindingCode =
  | "INVALID_INTENT"
  | "UNKNOWN_ASSET"
  | "SIMULATION_FAILED"
  | "UNDECODABLE_TRANSACTION"
  | "RECIPIENT_NOT_PAID"
  | "AMOUNT_MISMATCH"
  | "UNEXPECTED_ASSET_OUTFLOW"
  | "UNEXPECTED_RECIPIENT"
  | "UNDECLARED_APPROVAL"
  | "UNLIMITED_APPROVAL"
  | "APPROVAL_SPENDER_MISMATCH"
  | "APPROVAL_EXCEEDS_INTENT"
  | "APPROVAL_NOT_GRANTED"
  | "AUTHORITY_CHANGE"
  | "ACCOUNT_CLOSED"
  | "UNEXPECTED_SOL_TRANSFER"
  | "SOL_SPEND_EXCEEDS_CAP"
  | "UNKNOWN_PROGRAM"
  | "UNSUPPORTED_PROGRAM"
  | "SUPPLY_CHANGE"
  | "ACCOUNT_FROZEN"
  | "NEW_RECIPIENT"
  | "UNKNOWN_SPENDER"
  | "AMOUNT_ABOVE_REVIEW_THRESHOLD"
  | "AMOUNT_ABOVE_LIMIT";

/** Category for every finding code, so integrators can branch on the kind of failure. */
export const FINDING_CATEGORY: Record<FindingCode, FindingCategory> = {
  INVALID_INTENT: "INVALID_REQUEST",
  UNKNOWN_ASSET: "INVALID_REQUEST",
  UNDECODABLE_TRANSACTION: "UNSUPPORTED",
  UNSUPPORTED_PROGRAM: "UNSUPPORTED",
  SIMULATION_FAILED: "SIMULATION_FAILED",
  RECIPIENT_NOT_PAID: "INTENT_MISMATCH",
  AMOUNT_MISMATCH: "INTENT_MISMATCH",
  UNEXPECTED_ASSET_OUTFLOW: "INTENT_MISMATCH",
  UNEXPECTED_RECIPIENT: "INTENT_MISMATCH",
  UNDECLARED_APPROVAL: "INTENT_MISMATCH",
  APPROVAL_SPENDER_MISMATCH: "INTENT_MISMATCH",
  APPROVAL_EXCEEDS_INTENT: "INTENT_MISMATCH",
  APPROVAL_NOT_GRANTED: "INTENT_MISMATCH",
  AUTHORITY_CHANGE: "INTENT_MISMATCH",
  ACCOUNT_CLOSED: "INTENT_MISMATCH",
  UNEXPECTED_SOL_TRANSFER: "INTENT_MISMATCH",
  SUPPLY_CHANGE: "INTENT_MISMATCH",
  ACCOUNT_FROZEN: "INTENT_MISMATCH",
  UNLIMITED_APPROVAL: "POLICY_VIOLATION",
  SOL_SPEND_EXCEEDS_CAP: "POLICY_VIOLATION",
  UNKNOWN_PROGRAM: "POLICY_VIOLATION",
  NEW_RECIPIENT: "POLICY_VIOLATION",
  UNKNOWN_SPENDER: "POLICY_VIOLATION",
  AMOUNT_ABOVE_REVIEW_THRESHOLD: "POLICY_VIOLATION",
  AMOUNT_ABOVE_LIMIT: "POLICY_VIOLATION",
};
